create table users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    email varchar(150) not null,
    password varchar(255) not null,
    role varchar(20) not null,
    created_at timestamp with time zone not null,
    constraint uk_users_email unique (email)
);
