spring:
  application:
    name: authapp-code
  profiles:
    default: dev
  jpa:
    open-in-view: false

server:
  port: 8080

app:
  security:
    jwt:
      secret: ${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZg==}
      expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}
