spring:
  application:
    name: authapp-code
  profiles:
    default: dev
  jpa:
    open-in-view: false

server:
  port: 8080

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}
